// Manual AST interfaces for the floorplan language
// These would normally be generated by Langium

export interface Floorplan {
  floors: Floor[];
  connections: Connection[];
}

export interface Floor {
  id: string;
  rooms: Room[];
}

export interface Room {
  type: "room" | "sub-room";
  name: string;
  position: Coordinate;
  size: Dimension;
  walls: WallSpec;
  label?: string;
  subRooms?: Room[];
}

export interface WallSpec {
  specifications: WallSpecification[];
}

export interface WallSpecification {
  direction: WallDirection;
  type: WallType;
}

export interface Connection {
  from: WallReference;
  to: WallReference;
  doorType: DoorType;
  position?: number;
  opensInto?: RoomReference;
  swing?: SwingDirection;
}

export interface WallReference {
  room: RoomReference;
  wall?: WallDirection;
}

export interface RoomReference {
  name: string;
}

export interface Coordinate {
  x: number;
  y: number;
}

export interface Dimension {
  width: number;
  height: number;
}

export type WallDirection = "top" | "right" | "bottom" | "left";
export type WallType = "solid" | "door" | "window" | "open";
export type DoorType = "door" | "double-door";
export type SwingDirection = "left" | "right";
